apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-ingress-for-main
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.hostName }}
    secretName: {{ .Values.ingress.secret }}
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - path: /demo-app(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }}
            port:
              number: {{ .Values.service.port }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-ingress-for-static
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /static/$2
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.hostName }}
    secretName: {{ .Values.ingress.secret }}
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - path: /static(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }}
            port:
              number: {{ .Values.service.port }}