replicaCount: 1

appName: demo-app
configMapName: demo-app-configmap

CSI:
  name: demo-app-kv-provider
  kvName: "<< from command line >>"

image:
  repository: "<< from command line >>"
  tag: "latest"

resources:
  requests:
    memory: "1Gi"
  limits:
    memory: "1Gi"

service:
  type: ClusterIP
  port: 80

ingress:
  hostName: "<< from command line >>"
  secret: demo-app-tls-secret

nodePool: "<< from command line >>"

kvSecrets:
  secretA:
    kvName: NAME--FOR--SECRET--A--FROM--KEYVAULT
    k8Name: secret-name-for-a-if-k8s-secrets-are-used
    envName: SECRET_NAME_FOR_A_IF_ENV_VARIABLES_ARE_USED
  secretB:
    kvName: NAME--FOR--SECRET--B--FROM--KEYVAULT
    k8Name: secret-name-for-b-if-k8s-secrets-are-used
    envName: SECRET_NAME_FOR_B_IF_ENV_VARIABLES_ARE_USED

serviceAccount:
  name: "<< from command line >>"
  clientId: "<< from command line >>"
  tenantId: "<< from command line >>"

storage:
  storageClassName: demo-app-sc
  pvcName: demo-app-pvc
  resourceGroup: "<< from command line >>"
  storageAccount: "<< from command line >>"
  shareName: "<< from command line >>"
  protocol: smb
  server: "<< from command line >>"
  secretName: demo-app-storage-account-secret