name: ci-linter

on:
  pull_request:
    branches:
      - main

jobs:
  lint-markdown:
    name: markdown linting
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: lint markdown
        uses: avto-dev/markdown-lint@v1
        with:
          args: "**/*.md"